# Generated by Django 5.1.1 on 2024-12-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_message_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
