# Generated by Django 5.1.1 on 2024-12-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_event_date'),
        ('blog', '0005_comment'),
    ]

    operations = [
    ]
